//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warehousemanagementACE.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class warehousesEntities : DbContext
    {
        public warehousesEntities()
            : base("name=warehousesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<buying_invoice_p> buying_invoice_p { get; set; }
        public virtual DbSet<Buying_Invoives> Buying_Invoives { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Managers> Managers { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<selling_invoice_p> selling_invoice_p { get; set; }
        public virtual DbSet<Selling_Invoices> Selling_Invoices { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<Warehouses> Warehouses { get; set; }
    }
}
