//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warehousemanagementACE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class selling_invoice_p
    {
        public int S_I_Order_Number { get; set; }
        public int P_Id { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Selling_Invoices Selling_Invoices { get; set; }
    }
}
