//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warehousemanagementACE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selling_Invoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Selling_Invoices()
        {
            this.selling_invoice_p = new HashSet<selling_invoice_p>();
        }
    
        public int Order_Number { get; set; }
        public string W_Name { get; set; }
        public int C_Id { get; set; }
        public Nullable<System.DateTime> Selling_Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<selling_invoice_p> selling_invoice_p { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
